name: TestAutoScript

on:
  schedule:
    - cron: "30 22 * * *" # 每天UTC时间的22点，对应北京时间的早上6点
  workflow_dispatch:

env:
  VAR1: ${{ secrets.VAR1 }} # 从仓库的 secrets 中获取变量
  VAR2: ${{ secrets.VAR2 }} # 从仓库的 secrets 中获取变量
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} # 从仓库的 secrets 中获取变量

job:
  TestAutoScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          npm install
          npm run runAuto
